### ISSUE TITLE
FoLiA output samples do not validate

### ISSUE THREAD

**Issue by proycon** [A-Atef-NLP/CoreNLP2FoLiA#1]
Please ensure the output is valid FoLiA by checking it with ``foliavalidator`` (https://pypi.python.org/pypi/FoLiA-tools), or ``folialint`` (https://github.com/LanguageMachines/foliautils) or at the very least by checking against the RelaxNG schema.

**Comment by A-Atef-NLP** [comment]
Dear proycon,

    I am so sorry to be late. I checked it using XSLT and loaded it using MTAS to solr.
    You are correct i have to use FoLiA-tools, Sorry.
    If you have more details about this issue that will be nice from you.

Thanks A Lot

**Comment by proycon** [comment]
Thanks for looking into it, your project is very interesting so it would be great if is produces actual correct FoLiA. 

> I checked it using XSLT 

If you refer to the folia2html stylesheet, that doesn't really do any actual validation and is more tolerant to errors than the actual FoLiA libraries.

Currently I get this:

```
$ foliavalidator USA.txt.xml
VALIDATION ERROR against RelaxNG schema (stage 1/2), in USA.txt.xml
Element FoLiA failed to validate attributes, line 3
```

For a bit more verbosity I ran xmllint against the official FoLiA RelaxNG stylesheet manually:

```
$ xmllint --relaxng ~W/folia/schemas/folia.rng USA.txt.xml
```

I'll go through the output one by one:

```                                                                                 
USA.txt.xml:3: element FoLiA: Relax-NG validity error : Element FoLiA failed to validate attributes
```

You are missing the required ``xml:id`` attribute for the document as whole, each document needs to have an ID.  Though not strictly required, I also recommend adding ``version="1.2"`` (the FoLiA version you aim to support) and ``generator="CoreNLP2FoLiA"`` attributes.

```
USA.txt.xml:13: element meta: Relax-NG validity error : Element meta failed to validate attributes
```

Use ``id`` instead of ``xml:id`` here.

```
USA.txt.xml:13: element meta: Relax-NG validity error : Expecting element foreign-data, got meta
USA.txt.xml:13: element meta: Relax-NG validity error : Element metadata has extra content: meta
```

Caused by the previous error, will go away once that's fixed.

```
USA.txt.xml:214: element NormalizedNER: Relax-NG validity error : Element w has extra content: NormalizedNER
```
You can't add invent custom elements like this and add them to the FoLiA XML namespace; if you really want to add non-FoLiA elements, use ``foreign-data`` (see section 2.10.16 of the FoLiA documentation). But a proper FoLiA solution is always preferred, for this case you may want to look into the ``entity`` element (section 2.7.1).

```
USA.txt.xml:210: element w: Relax-NG validity error : Expecting an element t, got nothing
Relax-NG validity error : Extra element w in interleave
USA.txt.xml:184: element s: Relax-NG validity error : Element s failed to validate content
Relax-NG validity error : Extra element s in interleave
Relax-NG validity error : Extra element text in interleave
USA.txt.xml:15: element text: Relax-NG validity error : Element FoLiA failed to validate content
USA.txt.xml fails to validate
```

Cause by the previous error and will dissappear once ``NormalizedNER`` is gone, this document then validates. I assume similar issues are present in the other documents.

I hope this helps! Good luck!

**Comment by A-Atef-NLP** [comment]
Dear proycon,

    Thanks A lot for your support. 
    I fixed it, of course you can check and updated me if you face any issue.

   i am very appreciated your support.
